# Generated by Django 4.2.3 on 2023-07-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cook_alter_eating_options_alter_eating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cooks',
            field=models.ManyToManyField(to='main_app.cook'),
        ),
    ]
